### PR TITLE
Added enchantments to Gold Spade

### PR DESCRIPTION
**Pull request by UselessFodder**
as per Issue #46

### CODE REVIEW

**Comment by gmlaxfanatic** [comment]
Great. Mind fixing #48 while you are at it? I just got a message about that problem.  Also, be aware that I'm rewriting much of the java code, so I'd stay away from any of that on the master branch, I'm currently working on the schematics branch and am getting close to a working alpha version with a bunch of improvements. Let me know if you wanna know about that. Config fixes are great and will get carried through the rewrite, so its good you're addressing them.

Also, if you stick in "Fix #46" in the commit it will automatically link to the issue and close it when the pull is accepted which is nice.

**Comment by UselessFodder** [comment]
Okay, I hope I did it correctly. GitHub seems very nice, but it's a learning process.

Honestly, the chances of me touching the Java anytime soon are fairly low. I'm brand-spanking-new to Java and am quite rusty on OOP in general. So, I'll be glad to work with the config while I watch and learn from other's changes.

**Comment by gmlaxfanatic** [comment]
Sounds good! And yeah, github is great, and you seem to be picking it up nicely, the first few pull requests people make are generally huge messes but yours were fine.

**Comment by gmlaxfanatic** [comment]
Here's another issue if you wanna go at it (#50). Repairs should be a 10% of the total input cost, and are calculated by repair inputs multiplied by the repair multiple.

**Pull request merged**
