### PR TITLE
Printing press

### PR DESCRIPTION
**Pull request by pruby**
The press is now functional, though we may well want to tweak it to be a bit easier to use. I've described the functionality here:

https://github.com/gmlaxfanatic/FactoryMod/wiki/Printing-Press

How do we want to handle discussing costs and balancing? Send that link to /r/Civcraft ?

### CODE REVIEW

**Comment by pruby** [comment]
You're right, quotes in the config could be more consistent. It doesn't show up to the code though - quotes are stripped by the YAML parser as it's part of the format. I tend to use quotes whenever not doing a hash key - don't like implicit strings.

**Comment by gmlaxfanatic** [comment]
So I'm newish to github and have never had to manually merge  a pull request before, is this something where you can instead first pull from my repo, do the manual merge in your repo, and then submit another pull request that will then automatically merge? Because that would sure save me a lot of time learning how to do the manual merge and then merging it, if it isn't thats fine and I'll figure stuff out when I get some time. But file free to post a jar for CivTest right away, FactoryMod hasn't really been using that server for testing so it won't interfere with anything.

I've always just made a post suggesting a particular balance to the subreddit, if there is significant public opinion for changing whatever I suggest, I modify it to take into account the suggestions while still make some executive decisions myself, then I just send it to ttk. As long as there isn't huge public outcry, ttk won't care what you end up coding in terms of balance.

Also, the wiki doesn't seem to mention the signature in addition to the random number watermark, is that not implemented or just not mentioned there?

This should be really fun to try out with the ItemExchange mod I just put up on CivTest.

**Comment by pruby** [comment]
Ah, I don't see the "can't automatically merge" thing. I'll fix the conflict so you can. Normally on github you'd say "fix it" to the submitter :)

I'll mention the name in the wiki. It includes both the author of the original book and the number on security notes.

**Comment by pruby** [comment]
OK, should be possible to auto merge.

I just realised that the python scripts generate the whole config and I hadn't been changing them. I've adjusted them so that a bunch of the fixed config variables and the printing press stuff is in the template.yml , and the Python appends all the recipes, crafting portions to that. This makes it easy to add the large block of non-scripted config for the printing presses.

**Comment by pruby** [comment]
JAR of this branch packaged at https://github.com/pruby/FactoryMod-1/tree/package .

**Comment by gmlaxfanatic** [comment]
Great, thanks. I had forgotten about the config script issue, but I was going to suggest exactly that.

**Pull request merged**
