### PR TITLE
Redstone controlled factories

### PR DESCRIPTION
**Pull request by pruby**
This update provides redstone control for factories by connecting the redstone to the furnace block.

To make a factory redstone-sensitive it _must_ have a lever attached to the furnace. Without this, it will not be controlled by the redstone. A redstone pulse to redstone wire next to the furnace (any side) will turn the factory on if it's ready. Likewise, flipping the lever or pressing an additional button attached to the furnace block will count as a redstone pulse. _At the moment it will not respond to a repeater unless you also stick redstone on it_.

When the factory starts for any reason, the lever is switched to the on position. This sends out a redstone signal which can identify that the factory is running. When turned off for any reason, the factory is turned off. At the moment, turning the lever off by hand does nothing (hope to make this cancel the job in another update).

This can be combined with hoppers, etc, to build sophisticated factory control systems.

### CODE REVIEW

**Comment by pruby** [comment]
Added control to stop people from placing the lever on others' factories. Once you place the lever on a factory, others could activate it with redstone.

**Comment by pruby** [comment]
OK, added discussed controls. You have to explicitly allow a factory to be redstone activated by placing a lever on the furnace (which only someone with access can do). Any sneaky redstone tricks then are just part of the challenge. The redstone activation (input) and lever output features can each be disabled in the config if required.

Due to the nature of redstone, you're not going to be able to track who set it off in all cases and apply any permissions system. By placing a lever and allowing redstone activation, individuals can take responsibility for guarding the signals in to the factory or choose to avoid the risk. Snitches can log people messing with your factory, and others still can't load/unload it without access to the chest, which they can't get without putting the factory in a damaged state.

**Comment by gmlaxfanatic** [comment]
I'll send ttk a jar with this tonight. Since this is the most major update since 2.0 went live I don't know how he is dealing with testing things nowadays. I'll let him know the code looks fine but I don't have time to personally test it out. Once it goes up you should definitely make a post explaining the mechanic to the community and also write up a small piece I can stick in the github wiki so people have a reference for how to work with it. (Also, I didn't see you on the developers google group list, if you aren't in there you should ask ttk to pass you an invite)

**Comment by pruby** [comment]
Thank you, I'll write something up and pass ttk a changelog-style description.

**Pull request merged**
